// Generated by Wrangler on Fri Jul 19 2024 16:16:57 GMT+0700 (Western Indonesia Time)
// by running `wrangler types`

interface Env {
	MY_KV_NAMESPACE: KVNamespace;
	ENVIRONMENT: "dev";
	KEY: "value";
	SECRET_KEY: string;
}
